export const API_ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FAMILY_NOT_FOUND: 'FAMILY_NOT_FOUND',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_VIEW_FORBIDDEN: 'PROFILE_VIEW_FORBIDDEN',
  PROFILE_RECORD_FORBIDDEN: 'PROFILE_RECORD_FORBIDDEN',
  PROFILE_MANAGE_FORBIDDEN: 'PROFILE_MANAGE_FORBIDDEN',
  INVALID_BP_READING: 'INVALID_BP_READING',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  REMINDER_NOT_FOUND: 'REMINDER_NOT_FOUND',
  DUPLICATE_MEMBERSHIP: 'DUPLICATE_MEMBERSHIP',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES]

export type ApiError = {
  code: ApiErrorCode
  message: string
  requestId: string
  details?: Record<string, unknown>
}
